[package]
name = "tiff2"
version = "0.0.0"
edition = "2021"


[dependencies]
async-trait = "0.1.83"
bytemuck = { version = "1.19" }
bytes = "1.8"
flate2 = "1.0"
futures-lite = "2.3"
jpeg = { package = "jpeg-decoder", version = "0.3.0", default-features = false }
log = "0.4.22"
object_store = { version = "0.11.1", optional = true, features = ["http"] }
thiserror = "1.0"
weezl = "0.1.8"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
tokio = { version = "1.41", features = ["rt", "macros"] }

[features]
# default = ["object_store"]
object_store = ["dep:object_store"]

[[bench]]
name = "horizontal_predict"
harness = false
